#GET http://localhost:4004/odata/v4/product/printhelloworld(input='Hello')


#GET http://localhost:4004/rest/product/addition(num1=5,num2=10)

# Product 
#GET http://localhost:4004/odata/v4/productshop/Product

# Supplier
#GET http://localhost:33019/odata/v4/productshop/Supplier?$expand=product

#GET http://localhost:33019/odata/v4/productshop/Product?$expand=supplier&$select=name,category,rating



GET http://localhost:4004/odata/v4/productshop/products


POST http://localhost:33229/odata/v4/productshop/orderproduct
Content-Type: application/json

{
  "name": "Audi" ,
  "stock: 15"
}